version: '3.8'
services:
  registry:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"  # 允许删除镜像

  ui:
    image: joxit/docker-registry-ui:static
    restart: always
    ports:
      - "8083:80"
    environment:
      REGISTRY_URL: http://registry:5000
      DELETE_IMAGES: "true"  # 允许通过 UI 删除镜像
